options:
  jobs_load:
    table_name: jobs

    load_behavior:
      profile: full_refresh

      primary_key: id

      enable_hash: true
      hash_column: row_hash
      hash_columns:
        - title
        - company
        - location
        - description
        - job_type

      enable_generated_id: true
      generated_id_column: id
      generated_id_columns:
        - title
        - company
        - location

    runtime:
      full_load: true
      use_chunks: false
      extract_chunk_size: null
      write_chunk_size: null