options:
  jobs_load:
    table_name: jobs

    load_behavior:
      profile: historized_snapshot

      primary_key: id

      hash_column: row_hash
      hash_columns:
        - title
        - company
        - location
        - description
        - job_type

    runtime:
      extract_chunk_size: 3
      write_chunk_size: 6