sources:
  jobs_api_berlin:
    type: jobs_api
    resource_name: jobs
    config:
      search_term: data engineer scientist
      location: California
      results_wanted: 10

  local_jobs_csv:
    type: csv
    resource_name: jobs
    config:
      file_path: data/jobs.csv
