name: Copilot review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: copilot-code-review
        uses: AllyW/copilot-pr-review@v0.1.34
        with:
          AUTH_TOKEN: ${{ github.token }}
          APIKEY: ${{ secrets.APIKEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}